### ISSUE TITLE
Add content from Adobe XD to our current implementation

### ISSUE THREAD

**Issue by duff92** [AxessLab/typing#72]
**Describe the solution you'd like**
We need to add the missing content from the prototype.

Added sketches of the portotype for what we have in development. (Separate link to vectors in google drive folder.)
All:
https://xd.adobe.com/spec/940d8583-6287-4817-4227-92aeb4f4af2c-e23c/grid

- [x] #79 Add content to Intro start
- [x] #80 Add content to choose ninja
- [x] #81 Add content to explore mode
- [x] #82 Add content to challenge 1 instructions
- [x] #83 Add timer before task start
- [x] #84 Add content to task
- [x] #85 Add content to summery
- [ ] #86 Add go back modal

**Comment by duff92** [comment]
@duff92 and @sofieaxesslab Add remaining details to this issue.

**Comment by sofieaxesslab** [comment]
Alla vyer: 
https://xd.adobe.com/spec/940d8583-6287-4817-4227-92aeb4f4af2c-e23c/grid

1. Intro start (ej ljud på/av knapp):
https://xd.adobe.com/spec/940d8583-6287-4817-4227-92aeb4f4af2c-e23c/screen/fc8332b8-4bf5-4e1c-aae8-0d611b56043b/1-Start-intro

2. Choose ninja 
https://xd.adobe.com/spec/940d8583-6287-4817-4227-92aeb4f4af2c-e23c/screen/fa69c034-d743-4aee-b228-7807a2b52451/3-V-lj-ninja

3. Doruk 
https://xd.adobe.com/spec/940d8583-6287-4817-4227-92aeb4f4af2c-e23c/

4. Fousari
https://xd.adobe.com/spec/940d8583-6287-4817-4227-92aeb4f4af2c-e23c/screen/90299a59-e70f-410c-9999-cfdc313da517/4-2-V-l-ninja

5. Train/uppvärmning
https://xd.adobe.com/spec/940d8583-6287-4817-4227-92aeb4f4af2c-e23c/screen/c6687697-391c-4e7d-9a2e-51bb4e8be476/5-Uppv-rmning 

6. Challange 1 /Uppdrag 1 instruktioner
https://xd.adobe.com/spec/940d8583-6287-4817-4227-92aeb4f4af2c-e23c/screen/2bf9990f-6a18-4fa8-8c25-759fec4eaaa9/7-Uppdrag-1-instruktion

7. Challange 1 starts in.. timer
https://xd.adobe.com/spec/940d8583-6287-4817-4227-92aeb4f4af2c-e23c/screen/b68dc3bd-a7de-4ee3-9415-ea9c33ba85c5/8-1-Uppdrag-1-Startar-om-timer 

8.Uppdrag 1 / task 
https://xd.adobe.com/spec/940d8583-6287-4817-4227-92aeb4f4af2c-e23c/screen/3b7d34dc-be5a-47ad-a3db-9a60065f3e96/9-3-Uppdrag-1-F-J- 

9. Uppdrag 1 klart 
Först klart ljudslinga sedan läsa upp textinnehåll som i prototypen (inte du hade bara x fel).
https://xd.adobe.com/spec/940d8583-6287-4817-4227-92aeb4f4af2c-e23c/screen/d34db205-5953-426f-af83-1019f4496d9a/10-Uppdrag-1-Klar

10. Tillbakaknapp/Escape
https://xd.adobe.com/spec/940d8583-6287-4817-4227-92aeb4f4af2c-e23c/screen/430f9b38-f21c-4f85-accb-fd65ce927f2a/11-Tillbaka-knapp-r-du-s-ker-

**Comment by duff92** [comment]
Thanks @sofieaxesslab ! :) Adding this information in the description instead :)
